In [ ]:
import numpy as np

In [26]:
A = np.array ([[1,-1], [6,4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [32]:
from numpy.linalg import eig #import eigen value and eigen vector
eigval,eigvec = eig(A)
eigval,eigvec

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))

Matrix [1],[3] bukan merupakan eigenvector dari matrix A