In [1]:
import numpy as np

# Soal 1

In [6]:
from numpy import array


T = array ([[23, 50, 7, 12], [57, 67, 99, 43], [75, 21, 57, 12], [87, 26, 18, 84]])

In [7]:
T

array([[23, 50,  7, 12],
       [57, 67, 99, 43],
       [75, 21, 57, 12],
       [87, 26, 18, 84]])

# Soal 2

In [26]:
A = np.array([[23, 50, 19], [7, 12, 109],[57, 67, 98]])
B = np.array([[17], [22], [19]])

In [24]:
A,B

(array([[ 23,  50,  19],
        [  7,  12, 109],
        [ 57,  67,  98]]),
 array([[17],
        [22],
        [19]]))

In [28]:
C = A@B
C

array([[1852],
       [2454],
       [4305]])

# Soal 3

In [29]:
#Transpose
A.transpose()

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [34]:
#Determinan
from numpy.linalg import inv, det #import inv and determinan
det(A) 

131344.0000000002

In [36]:
#inverse
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])